services:
  - type: web
    name: mon-patrimoine-ci
    runtime: docker
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
